(function(z){
'use strict';var q7=function(a){z.L.call(this);this.aa(a)},Y5a=function(a,b){this.user=a;this.quotes=b},Z5a=function(a,b){b=b.g();if(b===Number||b.$isProtoEnum)return a=Number(a),Number.isNaN(a)?void 0:a;if(b===Boolean)return!!a;if(b===String)return String(a)},r7=function(a){return a.VB.best||null},s7=function(a,b){b=b.filter(function(a){return"anon"!=a.mb()});b=z.jb(b,function(a){return a.mb()},a);return z.nb(b).map(function(a){return new Y5a(a[0].ec(),a)},a)},$5a=function(a,b,c,d){return(0,z.Yc)(a.bu[b.name]||
[],function(a){return a.Ed()==c&&a.Be()==d})},t7=function(){this.HH=1},u7=function(a){z.Ch.call(this);this.aa(a)},a6a=function(a,b){return z.K(a,"slots",b)},b6a=function(a,b){return z.K(a,"requestContext",b)},v7=function(a){z.L.call(this);this.aa(a)},w7=function(a){return z.J(a,"inResponseToMediaResource")},x7=function(a){return z.J(a,"mediumQuote")},c6a=function(a,b){a.SQ=b;return a},y7=function(a,b){return r7(a)?z.QC(r7(a)).filter(function(a){return this.W5(a)==b},a):[]},d6a=function(a,b,c){c=c.ty;
b=b.getAttribute("name").split(" ");var d=z.zb(b);a=(a.bu[c.name]||[]).filter(function(a){return d[a.bj()]});return a.length?z.Hva(a):null},e6a=function(a,b,c,d){b=$5a(a,b,c,d);return s7(a,b)},f6a=function(a,b){var c=0;(a.bu[b]||[]).forEach(function(a){"anon"==a.mb()&&(c+=a.Le())});return c},g6a=function(a){var b=z.UM(a.ik.Et,a.ik.Xr(),a.nm.Et,a.nm.Xr()).Ia().trim();0<a.ik.Xr()&&(b="…"+b);var c=z.BD(a.yc,a.nm.Et);a.nm.Xr()<c.Ia().length&&(b+="…");return b},h6a=function(a){var b=z.tB(a.Zza),c=a.ik.Et,
d=c?b.indexOf(c):-1,e=(c=a.nm.Et)?b.indexOf(c):-1;if(-1==d||-1==e)return"";for(c=[];d<=e;d++)c.push(z.BD(a.yc,b[d]));b=z.Ra(c);a=z.st(c.indexOf(c[0]),a.ik.Xr(),c.indexOf(b),a.nm.Xr(),!1);return z.kka(new z.ft(z.bm,z.QDa),c,a,!0)},i6a=function(a,b,c){var d=a.ma.la(z.xDa,{postId:b},{filter:c});return z.nD(a,d,function(){return this.Cb.Om(d)})},j6a=function(a,b){z.Os(a,7);var c=new z.Fs("",1,a.Ia());b.forEach(function(a){z.Ms(c,z.ws(a.startOffset,a.endOffset,[a.quoteId],[a.userId]))},a);b=z.Yja(c);for(var d=
z.Zja(c,b),e=0;e<b.length;e++){var g=d[e];if(g.length){for(var k={},l=[],p=0;p<g.length;p++){var r=g[p];k[z.J(r,"creatorIds")]=!0;l.push(r.getName())}g=b[e];p=e<b.length-1?b[e+1]:a.Ia().length;z.Ms(a,z.ws(g,p,l,Object.keys(k)))}}},k6a=function(a,b,c){b="";a.JHa?a=z.n("Top highlight"):(c=""+z.A(z.jP(z.D({a7:!0,rma:!c.useragent.isMobile},a),c)),1==a.Hi&&a.isActive&&(a=z.n("highlighted"),c+=" "+a),a=(0,z.y)(c));b+=a;return(0,z.y)(b)},z7=function(a,b){this.ni=a;this.Gta=b;this.Pe=(this.Uk=b=z.oB(a.node,
b))&&b.getAttribute("name");this.DQ=b?z.pw(a,b):-1},A7=function(a){var b=a.length;a=a.match(l6a);if(!a)return b;for(var c=0;c<a.length;c++)b+=23-a[c].length;return b},m6a=function(a,b,c){return(0,z.y)(z.UO(z.D({user:c.currentUser,type:"quoteResponses"},a),c))},n6a=function(a,b,c){b="\x3cdiv class\x3d'u-marginLeft10'\x3e\x3cdiv class\x3d\"buttonSet u-inlineBlock\"\x3e"+z.A(z.ck({action:"quote",source:"quote_popover",icon:(0,z.N)(""+z.A(z.aea())),l:(0,z.N)("button--highlightMenu u-sm-height42 u-sm-lineHeight44 u-accentColor--highlightStrong js-quoteAttributions-pileOn"),
bc:!0,Uj:!0,FS:"quote",wa:!0,isActive:a.isActive},c))+(c.supportsEdit?z.A(z.ck({action:"quote-respond",source:"quote_popover",icon:(0,z.N)(""+z.A(z.fea())),l:"button--highlightMenu u-sm-height42 u-sm-lineHeight44",bc:!0,wa:!0},c)):"")+(a.vW?z.A(z.ck({action:"twitter",source:"quote_popover",icon:(0,z.N)(""+z.A(z.Pj(null))),l:"button--highlightMenu u-sm-height42 u-sm-lineHeight44",bc:!0,wa:!0},c)):"")+'\x3cdiv class\x3d"buttonSet-separator"\x3e\x3c/div\x3e\x3c/div\x3e';b+='\x3cdiv class\x3d"'+z.F(z.E("js-quoteAttributions-info u-inlineBlock u-verticalAlignTop u-noWrapWithEllipsis u-maxWidth414 u-paddingTop11 u-paddingRight18 u-paddingBottom0 u-paddingLeft10 u-xs-paddingTop13 u-xs-paddingLeft4 u-xs-maxWidth160"))+
'"\x3e'+k6a(a,0,c)+"\x3c/div\x3e\x3c/div\x3e";return(0,z.y)(b)},B7=function(a){z.dm.call(this);var b=z.vn();this.ik=b&&new z7(z.Xn(b,!0),a);this.nm=b&&new z7(z.Xn(b,!1),a)},C7=function(a){z.L.call(this);this.aa(a)},D7=function(a,b){var c=new z.hi(z.am(b)),c=new z.Nd(c.la(z.zCa)),d=new z.Nd("https://www.facebook.com/v2.7/dialog/share");z.Sd(d,z.ee({app_id:b.facebook.key,href:a.toString(),display:"popup",redirect_uri:c.toString()}));return d},o6a=function(a,b,c){function d(a){return a.replace(/“/g,
"‘").replace(/”/g,"’").replace(/„/g,"‚").replace(/'/g,"’")}b.content=d(b.content);b.name&&(b.name=d(b.name));var e=String(a(b,null,c)),g=A7(e)-280;0<g&&(b.content=z.kh(b.content,b.content.length-g),e=String(a(b,null,c)));return e},p6a=function(a,b){b=new z.hi(b.authBaseUrl);return new z.Nd(b.Dl(a))},q6a=function(){var a=z.n("Highlights");return(0,z.y)(""+a)},r6a=function(a,b,c){b=a.post.virtuals.responsesCreatedCount>=c.j.w8&&(a.post.creator.userId==c.currentUser.userId||(null==a.post.homeCollection?
null:null==a.post.homeCollection.virtuals?null:null==a.post.homeCollection.virtuals.permissions?null:a.post.homeCollection.virtuals.permissions.canManageAll));var d=z.D({q9:b},a),d=d||{},d=d.q9;a=""+('\x3cdiv class\x3d"container u-maxWidth740"\x3e\x3cdiv class\x3d"responsesStreamWrapper u-maxWidth640 u-hide js-responsesStreamWrapper"\x3e'+(0,z.y)('\x3cdiv class\x3d"container responsesStream-title u-paddingTop15"\x3e\x3cdiv class\x3d"row"\x3e'+z.A(z.yO({title:(0,z.N)(""+z.A(z.Lk())),ED:!0,Sg:(0,z.N)(""+
(c.supportsEdit&&d?z.wNa(null,c):""))},c))+"\x3c/div\x3e\x3c/div\x3e")+z.uNa(z.D({se:b},a),c)+(b?z.vNa(a,c):"")+z.tNa(c)+"\x3c/div\x3e\x3c/div\x3e");return(0,z.y)(a)},E7=function(a,b,c){z.P.call(this);this.xe=a.get("quotes-data");var d=this.xe.pp;d.subscribe("add",this.sfa,this);d.subscribe("remove",this.sfa,this);this.$a=b;this.Id=b.jm;this.vm=c;this.Uba=[];this.Ja=a.get("app");this.Ga=a.get("popover");this.ma=a.get("route-builder");this.L_=a.get("global-event-bus");this.kAa=a.get("progressive-media-loader")},
t6a=function(a,b,c,d){var e=s6a(a,b);if(e){var g=a.$a.isPublished(),k=z.cwa(a.$a);e.vW=g&&k;if(c=z.bG(z.oC(z.nC(z.pC(z.XE(z.qC(a.Ga).jb(n6a,e),z.YE),c),{M6:!0,Fy:!0,Ba:!0}),"popover--quoteAttributions"),d).ua())c.gn("deactivate",function(){this.Cp===b&&F7(this,null)},a),c.jo().ba("quote",a.Cua.bind(a,c)).ba("quote-respond",a.Dua.bind(a,c)).ba("twitter",a.Eua.bind(a))}},s6a=function(a,b){if("anon"==b.mb())return{isActive:!1,JHa:!0};var c=G7(a,b),d=b.Ed();b=b.Be();a=e6a(a.xe,c,d,b);if(!a||!a.length)return null;
a=(0,z.Bb)(a,function(a){return a.user});c=(0,z.Yc)(a,function(a){return a.userId!=z.Qp().userId});return{isActive:(0,z.Hc)(a,function(a){return a.userId==z.Qp().userId}),social:c,Hi:a.length}},u6a=function(a,b){a=a.Id.querySelectorAll('.markup--quote[name~\x3d"'+b.bj()+'"]');return z.ab(a)},G7=function(a,b){b=b.jc()[0].name;return(b=z.hs(a.Id,b))?a.$a.aj(b):null},v6a=function(a,b){var c=z.wn(b);return(c=z.yE(a.vm,c))?d6a(a.xe,b,c):null},F7=function(a,b){a.Cp!==b&&(a.Cp&&w6a(a,a.Cp,!1),b&&w6a(a,b,
!0),a.Cp=b)},w6a=function(a,b,c){u6a(a,b).map(function(a){z.cd(a,"is-targeted",c)})},H7=function(a,b){(b=x6a(a,b))&&z.wE(a.xk(),b)},x6a=function(a,b){var c=b.jc(),d=z.hs(a.Id,c[0].getName());a=z.hs(a.Id,z.Ra(c).getName());return z.UM(d,b.Ed(),a,b.Be())},I7=function(a,b,c,d){a={postId:a.$a.Na(),quoteId:b,source:d};z.mx(c?z.Ova:z.aFa,a)},y6a=function(a,b){z.sB(a,z.rB,z.Tb(b,z.Qb(!0)),void 0)},z6a=function(a,b,c){z.qa(a)||(a=a.toString());var d=window,e={scrollbars:!0,CKa:!0,toolbar:!1,location:!0,width:670,
height:690};z.wb(e,c||{});e.left||e.top||(e.width=(0,window.parseInt)(e.width,10),e.height=(0,window.parseInt)(e.height,10),e.left=Math.max(d.screenX+Math.round(d.outerWidth/2-e.width/2),0),e.top=Math.max(d.screenY+Math.round(d.outerHeight/2-e.height/2),0));var g={scrollbars:"scrollbars",CKa:"resizable",toolbar:"toolbar",location:"location",width:"width",height:"height",left:"left",top:"top"};c=z.lia(e,function(a,b,c){g[c]&&("boolean"==typeof b&&(b=b?"yes":"no"),a.push(g[c]+"\x3d"+b));return a},[]).join();
return d.open(a,b,c)},A6a=function(a){var b=z.Qv(z.Jxa,{HIa:!0});b&&(b=b.split(/\s+/),b=b.filter(function(a){return!z.Ea(a)}),b.length&&z.Uc(a,b))},B6a=function(a){return(0,z.y)(z.A(z.Kk(String(a.content)))+" — "+z.A(z.Wr(a))+" "+z.A(a.url))},C6a=function(a,b,c){return(0,z.ei)("https://"+z.Ng(c.textshotHost)+"/image")},D6a=function(a,b,c){return(0,z.ei)("https://twitter.com/"+z.Ng(c.currentUser.twitterScreenName)+"/status/"+z.Ng(a.id))},E6a=function(){var a=z.y,b;b=z.n("Failed to load image");b=(0,z.y)(""+
b);return a('\x3cspan class\x3d"tweetEditor-imageStatusIcon"\x3e\x26times;\x3c/span\x3e'+z.A(b))},F6a=function(a,b,c){b=z.y;a='\x3cdiv class\x3d"tweetEditor u-sizeFullWidth"\x3e\x3cdiv class\x3d"js-tweetEditor-error tweetEditor-error u-paddingBottom10 u-textAlignCenter u-textColorRed"\x3e\x3c/div\x3e\x3cdiv class\x3d"tweetEditor-avatar"\x3e'+z.A(z.$k({user:a.user,rf:!0},c))+'\x3c/div\x3e\x3cdiv class\x3d"tweetEditor-tweetContainer"\x3e\x3cdiv class\x3d"tweetEditor-textContainer"\x3e\x3cdiv class\x3d"js-tweetEditor-text textInput textInput--chromeless u-textAlignLeft"\x3e\x3c/div\x3e\x3c/div\x3e\x3cdiv class\x3d"tweetEditor-textshot"\x3e\x3cdiv class\x3d"js-tweetEditor-imageStatus tweetEditor-imageStatus"\x3e';
var d;d=z.n("Loading image attachment…");d=(0,z.y)(""+d);a=a+z.A(d)+"\x3c/div\x3e";d={};d=(0,z.y)(z.lj(z.D({name:"addCircled",size:"21px",content:(0,z.N)('\x3csvg class\x3d"svgIcon-use" width\x3d"21" height\x3d"21" viewBox\x3d"0 0 21 21" \x3e\x3cpath d\x3d"M2.286 12.691a8.358 8.358 0 0 0 2.192 3.831A8.298 8.298 0 0 0 8.3 18.715c.73.19 1.462.288 2.192.29a8.363 8.363 0 0 0 2.2-.29 8.286 8.286 0 0 0 3.822-2.193 8.264 8.264 0 0 0 2.201-3.82c.19-.732.285-1.462.285-2.193a8.248 8.248 0 0 0-.285-2.2 8.265 8.265 0 0 0-2.2-3.823 8.258 8.258 0 0 0-3.822-2.2A8.66 8.66 0 0 0 10.5 2a8.188 8.188 0 0 0-2.192.286 8.33 8.33 0 0 0-3.831 2.2 8.298 8.298 0 0 0-2.193 3.822A8.66 8.66 0 0 0 2 10.5c0 .731.095 1.461.286 2.191zm1.557-.413a6.74 6.74 0 0 1-.239-1.773c0-.592.08-1.184.24-1.773a6.77 6.77 0 0 1 1.786-3.09 6.73 6.73 0 0 1 3.085-1.79c.59-.16 1.181-.24 1.777-.24.596 0 1.188.08 1.777.24a6.736 6.736 0 0 1 3.094 1.786 6.801 6.801 0 0 1 1.787 3.094c.16.59.239 1.178.239 1.768 0 .59-.08 1.182-.24 1.778a6.75 6.75 0 0 1-1.786 3.093 6.801 6.801 0 0 1-3.094 1.787 6.707 6.707 0 0 1-3.545 0A6.74 6.74 0 0 1 5.63 15.37a6.746 6.746 0 0 1-1.787-3.093zm2.937-2.055c0-.134.049-.25.148-.345a.494.494 0 0 1 .359-.143H9.23a.478.478 0 0 0 .35-.148.475.475 0 0 0 .147-.35V7.303c0-.141.048-.262.144-.363a.458.458 0 0 1 .345-.152h.562c.134 0 .25.05.35.152a.502.502 0 0 1 .147.363v1.934c0 .135.048.252.143.35a.46.46 0 0 0 .345.148h1.945c.14 0 .26.048.358.143.099.096.148.21.148.345v.562a.476.476 0 0 1-.148.35.486.486 0 0 1-.358.147h-1.945a.472.472 0 0 0-.345.143.47.47 0 0 0-.143.345v1.944c0 .14-.05.262-.148.36a.478.478 0 0 1-.35.147h-.56a.498.498 0 0 1-.489-.507V11.77a.461.461 0 0 0-.148-.345.487.487 0 0 0-.35-.143H7.287a.488.488 0 0 1-.36-.147.476.476 0 0 1-.147-.35v-.562z" fill-rule\x3d"evenodd"/\x3e\x3c/svg\x3e')},
d)));d=(0,z.N)(""+z.A(d));var e;e=z.n("Include quote image");e=(0,z.y)(""+e);a=a+z.A(z.ck({icon:d,isPrimary:!0,wa:!0,l:"js-tweetEditor-addTextshot u-hide",action:"add-textshot",text:(0,z.N)(""+z.A(e))},c))+'\x3cdiv class\x3d"js-tweetEditor-imageContainer tweetEditor-imageContainer"\x3e';d=(0,z.N)("\x26times;");e=z.n("Remove quote image from tweet");e=(0,z.y)(""+e);return b(a+z.A(z.ak({s:d,Vc:!0,l:"js-tweetEditor-removeTextshot tweetEditor-removeTextshot",title:(0,z.N)(""+z.A(e)),action:"remove-textshot"},
c))+'\x3cimg class\x3d"js-tweetEditor-image tweetEditor-image" data-action\x3d"toggle-expand-image"\x3e\x3c/img\x3e\x3c/div\x3e\x3c/div\x3e\x3c/div\x3e\x3c/div\x3e'+(c.variants.textshots_userid?'\x3cdiv class\x3d"u-textColorRed"\x3eTweet to test account @fuzzyoctopusfee\x3c/div\x3e':""))},G6a=function(){var a=z.n("An error occurred, and the tweet wasn’t posted to Twitter.");return(0,z.y)(""+a)},H6a=function(a,b,c){var d="";b=z.n("Tweet posted.");a=a.PLa;var e;e=z.n("View the tweet");e=(0,z.y)(""+
e);d+=b+" "+z.A(z.O({wb:!0,href:a,s:(0,z.N)(""+e)},c));return(0,z.y)(d)},I6a=function(a,b,c){a=z.n("Tweet must be {$twitterMaxTweetLength} characters or less.",{twitterMaxTweetLength:z.A(c.j.QLa)});return(0,z.y)(""+a)},J6a=function(a){if(!a)return"";var b=[],c=z.ub(["grafId","noteId","command","startIndex","endIndex"]),d;for(d in a)b[c[d]]=a[d];return b.join("-")},J7=function(a){z.Ow.call(this);this.yc=a.get("dom-model-converter");this.mea={};this.fda={};this.M1={};this.qa=a;this.sl=a.get("request");
this.ma=a.get("route-builder");this.Aa=a.get("model-store");this.nb="";this.Qea=z.Ql;this.Rba=!1;this.Ih=null},K7=function(a,b){var c=a.mea[b];c||(c=a.mea[b]=new z.LC,a.za("new_note_list",c,a));return c},K6a=function(a,b){if(!b)return!1;var c=b.Ia();if(a.content==c.substring(a.startIndex,a.endIndex))return!0;var d=new RegExp(z.Ja(a.content),"gi"),c=(b=d.exec(c))&&d.exec(c);return b&&!c?(c=a.endIndex-a.startIndex,a.startIndex=b.index,a.endIndex=b.index+c,a.content=b[0],!0):!1},L7=function(a,b,c){var d=
b.Na(),e=b.zg(),g=K7(a,b.he()),k=g?g.indexOf(b):-1,l=b.oy();b.Qs(c);"HIDDEN"==c?a.Aa.remove(b):b=z.lC(a.Aa,b);var p=g?g.indexOf(b):-1;return{Il:a.sl.put(a.ma.la(z.ICa,{postId:d,noteId:e}),{state:c}),JL:function(){b.Qs(l);-1==p&&(-1==k?g.add(b):z.NC(g,b,k))}}},M7=function(a,b,c,d,e,g){var k=z.J(a.Qp(c,e),"replies"),l=z.Sa(k,function(a){return a.my()==b}),p=k[l];"HIDDEN"==g&&z.Wa(k,l);c=a.ma.la(z.LCa,{postId:d,noteId:c,replyId:b});a=a.sl.put(c,{state:g});var r=z.Sa(k,function(a){return a.my()==b});
return{Il:a,JL:function(){-1==r&&z.db(k,l,0,p)}}},L6a=function(a,b,c){this.range=a;this.anchor=b;this.pC=b.getAttribute("name");this.highlight=c},N7=function(a,b,c){z.P.call(this);this.$Aa=b;this.Wza=c;this.Oa=a.get("screen");this.eb=a.get("screen-request")},O7=function(a,b,c,d){z.P.call(this);this.Oa=a.get("screen");this.np=c;this.ph=d;this.aQ=!1;this.dw=this.kh=null;this.Wa(b)},P7=function(){},M6a=function(a){this.CQ=a},Q7=function(a,b){return b?z.hs(a.CQ,b):null},N6a=function(a,b,c){y6a(a.CQ,function(a){var e=
a.getAttribute("name");e&&b.call(c,a,e)})},O6a=function(a,b){return z.gg(a.CQ,b)?a.CQ:null},R7=function(a,b,c,d,e){z.SW.call(this,a,b);this.cb(new z.kW(c));this.cb(new z.fX(!1));this.cb(new z.iX(a));this.cb(new z.TW);this.cb(new z.lX(a,!1,!1));this.cb(new z.lU(d,!0));this.ml=!0;this.um=d;this.sl=a.get("request");this.Fa=a.get("dialog");this.q1=e;this.ua()},P6a=function(){var a=z.n("Saving failed. You may be having connectivity issues or notes might be disabled on this post. Please try again.");return(0,z.y)(""+
a)},Q6a=function(){var a=z.n("Yikes! Something happened and we couldn’t dismiss this note.");return(0,z.y)(""+a)},R6a=function(){var a=z.n("Yikes! Something happened and we couldn’t delete this note.");return(0,z.y)(""+a)},S6a=function(){var a=z.n("Yikes! Something happened and we couldn’t delete this reply.");return(0,z.y)(""+a)},T6a=function(){var a=z.n("The note has been dismissed.");return(0,z.y)(""+a)},U6a=function(){var a=z.n("The note has been deleted.");return(0,z.y)(""+a)},V6a=function(){var a=
z.n("The reply has been deleted.");return(0,z.y)(""+a)},W6a=function(){var a=z.n("Write a note…");return(0,z.y)(""+a)},X6a=function(){var a=z.n("Cancel");return(0,z.y)(""+a)},S7=function(a,b,c,d,e){R7.call(this,a,b,e||"Leave a note",400,d||null);this.nb=c;this.ma=a.get("route-builder");this.xf=a.get("notes-data")},T7=function(a,b,c,d,e,g){R7.call(this,a,b,"Leave a reply…",200,d);this.ma=a.get("route-builder");this.xf=a.get("notes-data");this.nb=c;this.ofa=g||null;this.Pe=e},Z6a=function(a,b,c){var d=
'\x3cdiv class\x3d"quoteResponses js-quoteResponses"\x3e',e=a.quotes.length,g=a.responses.length||a.R9;b=a.notes.length||a.tW;if(e||g||b){if(e){var e='\x3cdiv class\x3d"quoteResponses-section"\x3e'+z.A(z.Qy({title:(0,z.N)(z.A(q6a())+" ("+z.A(a.quotes.length)+")"),Vf:!0},c)),k;k={Ala:a.quotes,mMa:!0};var l='\x3cdiv class\x3d"js-quotesList"\x3e';if(!k.mMa)var p=z.n("Learn more"),l=l+z.A(z.Qy({title:(0,z.N)(""+z.A(q6a())),Vf:!0,Sg:(0,z.N)(""+z.A(z.Py({href:(0,z.M)(""+z.G((0,z.ei)("https://medium.com/the-story/introducing-highlights-a4df69e8ed43"))),
moreText:(0,z.N)(""+p),xb:!0},c)))},c));for(var p="list u-marginTop5 u-marginBottom15"+(k.Ala.length?"":" u-hide"),p=(0,z.N)(p),l=l+('\x3cul class\x3d"'+z.F(p)+'"\x3e'),p=k.Ala,r=p.length,u=0;u<r;u++){for(var w=p[u],C="",H=w.quotes,S=H.length,Q=0;Q<S;Q++)C+=""+H[Q].quoteId+(Q!=S-1?",":"");C=z.E(C);l+='\x3cli class\x3d"list-item list-item--inline u-border0" data-quote-ids\x3d"'+z.F(C)+'" data-quote-creator-id\x3d"'+z.F(w.user.userId)+'" data-action\x3d"highlight-quote" data-action-type\x3d"hover"\x3e'+
z.A(z.Yk(z.D({user:w.user,Fe:!0},k),c))+"\x3c/li\x3e"}k=(0,z.y)(l+"\x3c/ul\x3e\x3c/div\x3e");e=e+z.A(k)+"\x3c/div\x3e"}else e="";g?(g='\x3cdiv class\x3d"quoteResponses-section'+(a.R9?" is-withEditor":"")+'"\x3e'+z.A(z.Qy({title:(0,z.N)(""+z.A(z.Lk())),Vf:!0},c)),a.R9&&c.supportsEdit&&c.isAuthenticated?(k={},k=(0,z.y)('\x3cdiv class\x3d"js-inlineNewPostControl inlineNewPostControl inlineNewPostControl--quoteResponses"\x3e'+z.UO(z.D({user:c.currentUser,isCollapsed:!0,wD:!0,type:"quoteResponses",nv:(0,z.N)(""+
z.A(z.Ufa()))},k),c)+"\x3c/div\x3e"),k=z.A(k)):k="",g=g+k+Y6a(a,0,c)+"\x3c/div\x3e"):g="";d+=e+g;if(a.OJa&&b){g=z.n("Who can see this?");d+='\x3cdiv class\x3d"quoteResponses-section quoteResponses-section--fullBleed u-paddingLeft0 u-paddingRight0"\x3e';e=b="";k=a.post.homeCollection;k=a.post.creator.userId!=c.currentUser.userId?k?z.n("Private notes are visible to you, the author, and the editors of {$name}.",{name:z.A(k.name)}):z.n("Private notes are visible to you, the author, and the editors of any publication this story is added to."):
k?z.n("Private notes are visible to you and the editors of {$name}.",{name:z.A(k.name)}):z.n("Private notes are visible to you and the editors of any publication this story is added to.");e+=k;e=(0,z.y)(e);e=""+z.A(e);e=(0,z.N)(e);b+='\x3cspan data-tooltip\x3d"'+z.F(e)+'"\x3e'+g+"\x3c/span\x3e";g={};g=(0,z.y)(z.lj(z.D({name:"lock",size:"19px",content:(0,z.N)('\x3csvg class\x3d"svgIcon-use" width\x3d"19" height\x3d"19" viewBox\x3d"0 0 19 19" \x3e\x3cpath d\x3d"M14 14.052a1 1 0 0 1-.992.998H5.992A.99.99 0 0 1 5 14.052v-4.004a1 1 0 0 1 .992-.998h7.016a.99.99 0 0 1 .992.998v4.004zM7 5.445C7 4.187 8.114 3.15 9.5 3.15c1.385 0 2.5 1.04 2.5 2.295V8.05H7V5.445zm6.008 2.605H13V5.445c0-1.822-1.578-3.295-3.5-3.295C7.577 2.15 6 3.618 6 5.445V8.05h-.008A2 2 0 0 0 4 10.048v4.004a1.99 1.99 0 0 0 1.992 1.998h7.016A2 2 0 0 0 15 14.052v-4.004a1.99 1.99 0 0 0-1.992-1.998z" fill-rule\x3d"evenodd"/\x3e\x3c/svg\x3e')},
g)));g=(0,z.N)(""+z.A(g));e=z.n("Private notes");e=(0,z.y)(""+e);b={JLa:g,title:(0,z.N)(""+z.A(e)),Vf:!0,Sg:(0,z.N)(b),l:"heading--privateNotes"};b=(0,z.y)(z.Ny(z.D({Vi:(0,z.N)(""+z.Oy(b,c)),BIa:!0},b)));b=d+=z.A(b);d=""+('\x3cdiv class\x3d"privateNotes-list js-notesList'+(a.tW?" is-showingNoteEditor":"")+(0==a.notes.length?" is-empty":"")+'"\x3e');g=a.notes;e=g.length;for(k=0;k<e;k++)d+=U7({note:g[k],post:a.post,nM:a.nM},0,c);a.tW?(g=a.post.creator,a="",g=c.currentUser.userId==g.userId?z.n("Leave yourself a note"):
z.n("Send {$name} a private note…",{name:z.A(g.name)}),a+=g,a=(0,z.y)(a),a='\x3cdiv class\x3d"privateNotes-actions js-noteActions"\x3e'+z.A(z.bk({action:"show-note-editor",text:(0,z.N)(""+z.A(a)),l:"privateNotes-prompt"},0,c)),g=z.y,e='\x3cdiv class\x3d"privateNotes-editor"\x3e'+z.A(z.Zk({user:c.currentUser,rf:!0},c))+'\x3cdiv class\x3d"js-noteEditor"\x3e\x3c/div\x3e\x3cdiv class\x3d"buttonSet"\x3e',k=z.n("Send"),k=(0,z.y)(""+k),c=g(e+z.A(z.bk({action:"save-note",isPrimary:!0,l:"js-saveNoteButton",
text:(0,z.N)(""+z.A(k))},0,c))+z.A(z.bk({action:"hide-note-editor",text:(0,z.N)(""+z.A(X6a()))},0,c))+"\x3c/div\x3e\x3c/div\x3e"),c=a+c+"\x3c/div\x3e"):c="";c=(0,z.y)(d+("\x3c/div\x3e"+c));d=b+('\x3cdiv class\x3d"quoteResponses-inner privateNotes"\x3e'+c+"\x3c/div\x3e\x3c/div\x3e")}}else 0<a.rE&&(a=z.n("Show next tip"),b=z.n("Show previous tip"),d+='\x3cdiv class\x3d"quoteResponses-section quoteResponses-section--fullBleed quoteResponses-section--tips u-textAlignCenter u-paddingLeft0 u-paddingRight0"\x3e\x3cdiv class\x3d"quoteResponses-section--tipsInner u-alignMiddle"\x3e'+
z.A(z.ck({Db:!0,Vc:!0,wa:!0,action:"previous-highlight-tip",icon:(0,z.N)(""+z.A(z.Rda())),title:(0,z.N)(""+b)},c))+"\x3cdiv class\x3d'u-alignBlock quoteResponses-section--tipsContent u-paddingLeft20 u-paddingRight20 js-highlightTip'\x3e\x3c/div\x3e"+z.A(z.ck({Db:!0,Vc:!0,wa:!0,action:"next-highlight-tip",icon:(0,z.N)(""+z.A(z.Sda())),title:(0,z.N)(""+a)},c))+"\x3c/div\x3e\x3c/div\x3e\x3c/div\x3e");return(0,z.y)(d+"\x3c/div\x3e")},Y6a=function(a,b,c){return(0,z.y)(z.A(z.mQ({posts:a.responses,source:"quoteResponses",
vU:!0},0,c)))},U7=function(a,b,c){var d,e=null==a.note.replies?null:a.note.replies.length,g=null==a.note.replyId,k=a.post.creator.userId==c.currentUser.userId,l=a.post.creator.userId==a.note.author.userId;d=a.note.author.userId==c.currentUser.userId;b=k||(null==a.post.homeCollection?null:a.post.homeCollection.virtuals.permissions.canEditPosts);var p=""+(g?"js-note-item"+(a.note.noteId?" js-note-"+a.note.noteId:""):"js-reply-item"+(a.note.replyId?" js-reply-"+a.note.replyId:"")),p=z.E(p),p='\x3cdiv class\x3d"privateNotes-item '+
z.F(p)+' js-note" data-note-id\x3d"'+z.F(a.note.noteId)+'"\x3e'+(g?z.A(z.Yk({user:a.note.author},c)):z.A(z.UN({user:a.note.author},c)))+'\x3cdiv class\x3d"privateNotes-authorLockup"\x3e\x3cdiv class\x3d"privateNotes-author"\x3e'+z.A(z.yk({user:a.note.author},c));g||!(k||d||(null==a.post.homeCollection?0:a.post.homeCollection.virtuals.permissions.canEditPosts))||l||a.$ja?k="":(k=z.n("(Editor)"),k=(0,z.y)(""+k),k='\x3cspan class\x3d"privateNotes-author--supplemental"\x3e '+z.A(k)+"\x3c/span\x3e");p=
p+k+'\x3c/div\x3e\x3cdiv class\x3d"privateNotes-supplemental"\x3e'+z.A(z.ch(Number(a.note.createdAt),c))+'\x3c/div\x3e\x3c/div\x3e\x3cdiv class\x3d"privateNotes-content js-privateNotesContent"\x3e';k=z.A(z.It(String(a.note.content),c));l=String(k).replace(/(\r\n|\r|\n)/g,"\x3cbr\x3e");k=z.ng(k,z.pg)?(0,z.y)(l,z.zca(k)):l;d=""+(p+k+"\x3c/div\x3e"+(d?$6a({note:a.note,isPrimary:g},c):""));if(g){d+='\x3cdiv class\x3d"privateNotes-replies'+(e?"":" is-empty")+' js-repliesList"\x3e';if(e)for(e=a.note.replies,
g=e.length,p=0;p<g;p++)k=e[p],d+=U7({note:k,post:a.post,$ja:a.note.author.userId==k.author.userId},0,c);e=d;a.nM?(g=z.y,d='\x3cdiv class\x3d"privateNotes-editor privateNotes-editor--reply"\x3e'+z.A(z.uQ({user:c.currentUser,rf:!0},c))+'\x3cdiv class\x3d"js-replyEditor"\x3e\x3c/div\x3e\x3cdiv class\x3d"buttonSet"\x3e',p=z.n("Send"),p=(0,z.y)(""+p),g=g(d+z.A(z.bk({action:"save-reply",isPrimary:!0,text:(0,z.N)(""+z.A(p))},0,c))+z.A(z.bk({action:"hide-reply-editor",text:(0,z.N)(""+z.A(X6a()))},0,c))+"\x3c/div\x3e\x3c/div\x3e")):
g="";g="\x3c/div\x3e"+g+'\x3cdiv class\x3d"privateNotes-actions'+(b?" privateNotes-actions--withDismiss":"")+' u-clearfix"\x3e';a.nM?(d=z.y,p=z.n("Reply"),p=(0,z.y)(""+p),d='\x3cdiv class\x3d"u-floatLeft"\x3e'+d(z.A(z.bk({isPrimary:!0,action:"show-reply-editor",l:"privateNotes-prompt",text:(0,z.N)(""+z.A(p))},0,c)))+"\x3c/div\x3e"):d="";d=e+(g+d+(b?'\x3cdiv class\x3d"u-floatRight"\x3e'+$6a({note:a.note,isPrimary:!0,Hja:!0},c)+"\x3c/div\x3e":"")+"\x3c/div\x3e")}return(0,z.y)(d+"\x3c/div\x3e")},$6a=
function(a,b){var c=z.y,d=a.isPrimary?a.note.noteId:a.note.replyId,e=a.Hja?"dismiss-note":a.isPrimary?"delete-note":"delete-reply";a=a.Hja?z.n("Dismiss note"):z.n("Delete");a=(0,z.y)(""+a);a=z.A(a);return c(z.A(z.bk({actionValue:d,action:e,l:"privateNotes-delete js-deleteNote",text:(0,z.N)(""+a)},0,b)))},a7a=function(a,b,c){b="";if(0==a.F9)a=1==a.rE?z.n("People highlighted this passage. You can click on an existing highlight to add to it, like below:"):z.n("{$topQuoteCount} people highlighted this passage. You can click on an existing highlight to add to it, like below:",
{topQuoteCount:z.A(a.rE)}),b+=a,b+='\x3cimg class\x3d"quoteResponses-tipAnimation" src\x3d"'+z.F(z.Sg(z.Xi({imageId:"1*SyXCciYXeNpx4-GUAuh0XQ.gif"},0,c)))+'"\x3e';else if(1==a.F9)a=z.n("Or, select any passage to create your own highlight and tell the author and others what resonated with you:"),b+=a+'\x3cimg class\x3d"quoteResponses-tipAnimation" src\x3d"'+z.F(z.Sg(z.Xi({imageId:"1*dEp02HXMKtAeKxsV5MWqGg.gif"},0,c)))+'"\x3e';else if(2==a.F9){a=z.n("so that you can save your highlights and share them with others.");
var d=z.n("Sign up and create a profile");b+=z.A(z.bk({text:(0,z.N)(""+d),bc:!0,source:(0,z.N)(""+z.A(z.gi({name:c.j.Qc.soa,susiEntry:c.j.Ha.bF}))),l:"u-textUnderline"},0,c))+" "+a}return(0,z.y)(b)},V7=function(a,b,c,d,e,g,k,l){z.P.call(this);this.qa=a;this.xa=a.get("butter-bar");this.$a=b;this.Pe=c;this.dk=e;this.xe=a.get("quotes-data");this.xf=a.get("notes-data");this.Bj=a.get("responses-data");this.lf=g;this.q1=d;this.r2=(this.wI=k)?k.bj():null;this.Mf=this.Hc=null;this.fk={};this.rda=!!z.Rp();
this.sda=!!z.Tp();this.mB=this.rda&&this.sda&&z.OE(b);this.cr=null;this.LP=0;this.vga=f6a(this.xe,this.Pe);this.Iw=l;this.Wa(this.Tq());this.qea=z.Rp()?2:3},b7a=function(a){a.qb(".js-block").forEach(function(a){this.Ta(a,"mouseenter",this.cva,this);this.Ta(a,"mouseleave",this.O3,this)},a)},c7a=function(a){a.qb(".js-note").forEach(function(a){this.Ta(a,"mouseenter",this.ava,this);this.Ta(a,"mouseleave",this.O3,this)},a)},d7a=function(a,b){var c=a.query(".js-note-"+b);a.fk[b]||(a.fk[b]=new T7(a.qa,
c.querySelector(".js-replyEditor"),a.$a.Na(),b,a.Pe),z.Qw(a,a.fk[b],"saving",a.Aya,a),z.Qw(a,a.fk[b],"save",a.vya,a),z.Qw(a,a.fk[b],"fail",a.txa,a));z.Tc(c,"is-noteEditorVisible");a.fk[b].focus()},e7a=function(a,b){var c=a.fk[b];c&&(c.ib()&&c.hd(""),a=a.query(".js-note-"+b),z.$c(a,"is-noteEditorVisible"))},f7a=function(a,b,c){var d=Q7(a.lf,a.Pe);if(d){var e=[];a.Iw&&(e=a.Iw.quotes.map(function(a){return a.bj()}));(0,z.Bb)(d.querySelectorAll(".markup--quote"),function(a){var d=a.getAttribute("data-creator-ids").split(" "),
d=z.Va(d,b);if(this.Iw)var l=a.getAttribute("name").split(" "),d=d&&(0,z.Hc)(l,z.Va.bind(null,e));z.cd(a,"is-selected",c&&d)},a)}},W7=function(a){return(a=z.es(a,function(a){return z.Rc(a,"js-note-item")}))&&a.getAttribute("data-note-id")},g7a=function(a,b,c,d){b=new z.CE(b,300);b.Wa(c);b.subscribe("dismiss",d,a);b.ua();return b},X7=function(a){var b=a.jc(),c=a.Ed();a=a.Be();1<b.length&&(a=b[0].Ia().length);var d=new z.Qr;d.rq(b[0].getName());d.Ig(c);z.K(d,"endIndex",a);d.hd(b[0].Ia().substring(c,
a));return d},Y7=function(a,b){b%=a.qea;0>b&&(b=a.qea-1);a.LP=b;(b=a.query(".js-highlightTip"))&&z.Pv(b,a7a,{F9:a.LP,rE:a.vga})},Z7=function(a,b,c,d){z.P.call(this);this.Wa(this.Tq(d));this.Fb=a.get("dom-monitor");this.$a=b;this.xda=!b.Ya().Wr()||b.Mb();this.nb=b.Na();this.lf=c;this.xe=a.get("quotes-data");this.Bj=a.get("responses-data");this.xf=a.get("notes-data");this.nw=null;this.Lh={}},h7a=function(a,b){b.forEach(function(a){a&&$7(this,a)},a)},$7=function(a,b){if(!a.nw)if(Q7(a.lf,b)){var c=i7a(a,
b),c=j7a(a,c),c=k7a(a,c),c=l7a(a,c);a.Lh[b]=c;m7a(a,b)}else delete a.Lh[b]},n7a=function(a,b){if(!a.nw){var c=a.Lh[b];if(c){var d=c.length,c=k7a(a,c),c=l7a(a,c);a.Lh[b]=c;d!=c.length?m7a(a,b):c.forEach(function(a){a.Xa&&a.offsetTop&&(a.Xa.style.top=a.offsetTop+"px")})}}},o7a=function(a,b,c){return z.Ta(a.Lh[b]||[],function(a){return a.Xa==c})},i7a=function(a,b){var c=[];K7(a.xf,b).Vg(function(a){var e=a.WC(),g;e?(g=this.xf.QT(e),e=g.kb(),g=z.J(g,"endIndex")):(e=0,g=a.ib().length);c.push({anchor:b,
startIndex:e,endIndex:g,notes:[a],quotes:[],responses:[]})},a);if(a.xda)return c;(a.xe.bu[b]||[]).forEach(function(a){var e=p7a(a);c.push({anchor:b,startIndex:e.startIndex,endIndex:e.endIndex,notes:[],quotes:[a],responses:[]})},a);y7(a.Bj,b).forEach(function(a){var e=w7(a);e&&(e=x7(e)&&x7(e).io())&&(e=p7a(e),c.push({anchor:b,startIndex:e.startIndex,endIndex:e.endIndex,notes:[],quotes:[],responses:[a]}))},a);return c},j7a=function(a,b){var c=[];b.sort(function(a,b){return a.startIndex-b.startIndex});
b.forEach(function(a){var b=z.Sa(c,function(b){return b.endIndex>=a.startIndex-1&&b.startIndex<=a.endIndex+1});0<=b?this.VH(c[b],a):c.push(a)},a);return c},l7a=function(a,b){var c=[];b.forEach(function(a){if(a.offsetTop){var b=z.Sa(c,function(b){return 30>=Math.abs(b.offsetTop-a.offsetTop)});0<=b?this.VH(c[b],a):c.push(a)}},a);return c},m7a=function(a,b){a.qb(".js-paragraphControl-"+b).forEach(z.Vf);a.Lh[b]=a.Lh[b].map(function(a){var b=q7a(this,a),b=z.Rv(r7a,b);b.style.top=a.offsetTop+"px";a.Xa=
b;this.oa().appendChild(a.Xa);z.Tc(b,"is-visible");return a},a)},q7a=function(a,b){var c=b.notes,d=b.responses,e=s7(a.xe,b.quotes),g=d?d.length:0,k=c?c.length:0,l=0,p=0,r=0,u=!1,w=!1,C={},H={},S=z.Qp().userId,Q=a.$a.Ya().Af().mb();c.forEach(function(a){var b=a.hK();b&&((a=z.J(a,"replies"))&&a.forEach(function(a){k++;a.author&&(a.author.userId==S&&l++,a.author.social&&a.author.social.isFollowing&&(C[a.author.userId]=a.author),H[a.author.userId]=!0)}),H[b.userId]=!0,b.userId==S&&l++,b.userId==Q?p++:
r++,b.social&&b.social.isFollowing&&(C[b.userId]=b))});e.forEach(function(a){a=a.user;H[a.userId]=!0;a.userId==S&&(u=!0);a.social&&a.social.isFollowing&&(C[a.userId]=a)});d.forEach(function(a){a=a.Af();H[a.userId]=!0;a.userId==S&&(w=!0);a.social&&a.social.isFollowing&&(C[a.userId]=a)});c=b.quotes.filter(function(a){return"anon"==a.mb()});return{postId:a.nb,pC:b.anchor,MJa:k,DKa:g,$y:w,Ry:l,Wka:p,NJa:r,z2a:e.length,Zy:u,vja:Object.keys(H).length,AHa:z.nb(C),rE:c.length}},p7a=function(a){var b=a.Ed(),
c=a.Be();1<a.paragraphs.length&&(c=a.paragraphs[0].text.length);return{startIndex:b,endIndex:c}},k7a=function(a,b){var c=z.lw();return b.map(function(a){var b=this.lf.get(a.anchor),g=this.$a.aj(b);if(!g)return a;var k;4==g.type&&(g.Ia()&&(k=b.querySelector("figcaption")),k||(k=b));if(!k){g=a.startIndex+1;b=[b];k=0;for(var l=null;0<b.length&&k<g;)if(l=b.pop(),!(l.nodeName in z.sKa))if(3==l.nodeType){var p=l.nodeValue.replace(/(\r\n|\r|\n)/g,"").replace(/ +/g," ");k+=p.length}else if(l.nodeName in z.UQ)k+=
z.UQ[l.nodeName].length;else for(p=l.childNodes.length-1;0<=p;p--)b.push(l.childNodes[p]);k=l}g=z.ow(k,!0);a.offsetTop=Math.round(g.top+c.top);return a},a)},r7a=function(a,b,c){b=z.y;var d='\x3cdiv class\x3d"paragraphControls js-paragraphControl js-paragraphControl-'+z.F(a.pC)+' u-noUserSelect"\x3e',e=z.y,g;if(a.MJa||a.DKa){g='\x3cdiv class\x3d"notesMarker u-noUserSelect" data-action\x3d"select-anchor" data-action-value\x3d"'+z.F(a.pC)+'"\x3e';var k;k={};k=(0,z.y)(z.lj(z.D({name:"asteriskFilled",
size:"19px",content:(0,z.N)('\x3csvg class\x3d"svgIcon-use" width\x3d"19" height\x3d"19" viewBox\x3d"0 0 19 19" \x3e\x3cpath d\x3d"M14.78 8.07a8.681 8.681 0 0 0-.427-1.383.478.478 0 0 0-.584-.27l-3.12.77V4.034c0-.247-.19-.48-.43-.5a7.23 7.23 0 0 0-1.38 0c-.24.02-.43.253-.43.5V7.19L5.3 6.415a.48.48 0 0 0-.583.27c-.18.448-.324.91-.426 1.383-.05.24.1.5.32.58l3.06.754-1.98 2.956c-.14.196-.13.502.04.67.34.332.7.632 1.09.896.2.136.49.077.63-.117l2.09-3.114 2.09 3.112c.15.193.43.252.63.116.39-.26.75-.56 1.09-.89.17-.17.19-.47.04-.67L11.4 9.41l3.06-.76a.517.517 0 0 0 .32-.58" fill-rule\x3d"evenodd"/\x3e\x3c/svg\x3e')},
k)));g=g+z.A(k)+"\x3c/div\x3e"}else g="";var l=k="",p="",r=1==a.Ry?z.n("a note"):z.n("notes"),p=p+(""+r),p=z.E(p);1==a.vja&&(0<a.Ry||a.Zy||a.$y)&&(0<a.Ry&&a.Zy&&a.$y?(p=z.n("highlighted, responded, and left {$noteCountText}",{noteCountText:""+p}),l+=" "+p):0<a.Ry&&a.$y?(p=z.n("responded and left {$noteCountText}",{noteCountText:""+p}),l+=" "+p):0<a.Ry&&a.Zy?(p=z.n("highlighted and left {$noteCountText}",{noteCountText:""+p}),l+=" "+p):a.Zy&&a.$y?(p=z.n("highlighted and responded"),l+=" "+p):a.Zy?
(p=z.n("highlighted"),l+=" "+p):0<a.Ry?(p=z.n("left {$noteCountText}",{noteCountText:""+p}),l+=" "+p):a.$y&&(p=z.n("responded"),l+=" "+p));l=z.E(l);k+='\x3cspan class\x3d"paragraphControls-itemText"\x3e';p="";if(0<a.Wka&&0==a.NJa&&!a.Zy&&!a.$y)c=1==a.Wka?z.n("Note to self"):z.n("Notes to self"),p+=c;else{r="";if(0<a.rE)var u=z.n("Top highlight"),r=r+u;p+=z.A(z.jP(z.D({social:a.AHa,isActive:0<a.Ry||a.Zy||a.$y,Hi:a.vja,a7:!0,ZJa:!0,Vha:(0,z.N)(r)},a),c));p+=z.A(l)}p=(0,z.N)(p);k+=z.A(z.MIa(z.D({text:p},
a)))+"\x3c/span\x3e";a=(0,z.y)(k);a=e(g+a);return b(d+a+"\x3c/div\x3e")},a8=function(a,b,c){z.P.call(this);this.qa=a;this.Ja=a.get("app");this.Kta=a.get("floating-components");this.Oa=a.get("screen");this.tb=a.get("screen-service");this.Fb=a.get("dom-monitor");this.$a=b;this.Id=b.Id;this.jm=this.Id.querySelector(".js-postField");this.Jea=this.Oa.oa().querySelector(".js-notesPositionContainer");this.xe=a.get("quotes-data");this.xf=a.get("notes-data");this.xf.subscribe("new_note_list",this.Rxa,this);
this.Bj=a.get("responses-data");this.im=null;this.lf=new M6a(this.Id.querySelector(".js-notesSource"));this.RH=this.Lh=this.rR=null;this.Lh=new Z7(a,b,this.lf,this.Jea);this.track(this.Lh);this.RH=this.Lh.oa();this.kh=this.S0=null;this.Re=c},c8=function(a,b){if(a.isActive()){var c=(b=b||a.S0)&&b.oU,d=b&&b.noteId;c&&(a.ix(c),d&&a.xf.Qp(d,c)&&a.kh&&z.t(a.kh,function(){return b8(a,c,null,d)}));z.poa(a.Ja,"")}else a.S0=b||null},b8=function(a,b,c,d,e,g){var k={Vl:!0,T6:z.Vv()};a.A2();c=new V7(a.qa,a.$a,
b,d||"",c||null,a.lf,e||null,g||null);c.subscribe("set-active-highlight",a.Efa,a);c.subscribe("reset-highlight",a.hBa,a);c.subscribe("close",a.A2,a);b=g&&g.Xa?g.Xa:a.lf.get(b);g=z.lya(a.Kta);g.Pn=b;b=g.vE(c);b.pJ=k;k=b.fX(a.Jn.bind(a));k.lR=!0;a.im=k.ua()},s7a=function(a,b,c){var d=a.$a.aj(Q7(a.lf,b));if(d&&4!=d.type){z.Os(d,4);if(c){if(!K6a(c,d))return;z.Ms(d,z.vs(c.startIndex,c.endIndex,c.id))}c=a.$a.Mb();var e=a.$a.Ya();c={mode:c?"edit":"view",Pj:z.at(e),media:null,$l:null,sections:!0,Hk:!1,Ek:!1,
Fl:!1,Pf:!1,postId:e.id};a.lf.get(b).innerHTML=z.xt(d,z.bm,c)}},t7a=function(a,b){var c=z.vn();if(!c||c.isCollapsed())if(b&&(c=b),!c||c.isCollapsed())return null;b=c.Tf();var d=O6a(a.lf,b);if(!d)return null;a=(b=z.es(b,z.rB,d))&&a.$a.aj(b);if(!b)return null;var d=z.qw(c,b,!0),e=z.qw(c,b,!1);return-1==d||-1==e?null:new L6a(c,b,new z.Qr({anchor:b.getAttribute("name"),startIndex:d,endIndex:e,content:a.Ia().substring(d,e)}))},u7a=function(){},d8=function(a,b){z.P.call(this);this.Ph=b||r6a;this.eb=a.get("screen-request");
this.va=null;this.Z3=a.get("screen-view-state");this.qa=a;this.Rfa=this.d3=!1;this.K1=this.Hc=null},e8=function(a){z.Ow.call(this);this.zz=a},v7a=function(a,b,c){a=z.qa(a)?new z.Nd(a):a;(a=z6a(a,b,c||{}))&&(new e8(a)).focus()},w7a=function(a){this.pa=a.get("request");this.ma=a.get("route-builder")},f8=function(a){z.dm.call(this);this.qa=a;this.uG=a.get("dialog");this.pa=a.get("request");this.ma=a.get("route-builder");this.xa=a.get("butter-bar");this.wJ=this.Fa=this.Ax=this.va=null;this.SP=!1},y7a=
function(a){var b=a.Fa.query(".js-tweetEditor-image"),c=a.Fa.query(".js-tweetEditor-imageContainer"),d=a.Fa.query(".js-tweetEditor-imageStatus");z.Tc(c,"u-hide");var e=x7a(a);e.base64=!0;z.v(z.t(a.pa.post(z.Qv(C6a),e,{qC:!1,withCredentials:!1}),function(a){b.src="data:image/png;base64,"+a;z.$c(c,"u-hide");z.Tc(d,"u-hide");this.SP=!0},a),function(a){z.Kw(a);z.Pv(d,E6a)},a)},z7a=function(a,b){return 280>=A7(b)?!0:(b=a.Fa.query(".js-tweetEditor-text"),(new z.sz(b,{name:"shimmy-shake",duration:400})).start(),
a=a.Fa.query(".js-tweetEditor-error"),z.Pv(a,I6a),!1)},x7a=function(a){var b=a.va,c=a.Ax.GLa;a=a.Ax.FLa;var d=b.creator,e=b.approvedHomeCollection,g=z.bm,k=null;e&&(k=e.image);var l=null;e&&e.logo&&e.logo.imageId&&(l=e.logo.imageId);var p=null;e&&e.tintColor&&2==e.colorBehavior&&e.logo&&e.logo.imageId&&(p=e.tintColor);var r=null;e&&e.tintColor&&(r=z.kKa(e.tintColor),r=z.Cr(r,.6).color);return new C7({content:c,altText:a,title:b.title,author:d&&d.name,date:z.bh(b.createdAt,g),authorAvatarId:d&&d.imageId,
collection:e&&e.name,collectionAvatarId:k?k.imageId:null,collectionLogoId:l,collectionBackgroundColor:p,collectionHighlightColor:r,version:2})},A7a=function(a){this.pa=a.get("request");this.ma=a.get("route-builder");this.qa=a};z.q(q7,z.L);z.f=q7.prototype;z.f.ca=function(){return""};z.f.ea=function(){return"Placement"};z.f.sf=function(){return z.J(this,"items")};z.f.Kc=z.h(393);z.f.eM=function(a){return z.K(this,"location",a)};z.f.Dd=z.h(436);z.f.Yb=function(a){return z.K(this,"index",a)};
z.f.ha=function(){return q7.prototype};z.f.fa={name:"Placement",ia:!1,fields:{items:{name:"items",g:function(){return z.ZL},ra:z.U,h:1},location:{name:"location",g:function(){return z.CBa},h:2},index:{name:"index",g:z.W,h:3}},ka:{}};z.f.Dd=z.X(436,function(){return z.J(this,"index")});z.f.Kc=z.X(393,function(a){return z.K(this,"items",a)});z.m(t7,z.se);t7.prototype.wk=function(a){var b={};z.lD(this,b,a.Pb(),"");return b};
t7.prototype.Jb=function(a,b){if(!a||!b)return null;var c=new a;Object.keys(b).forEach(function(a){for(var e=a.split(/[[\]]+/).filter(function(a){return!!a}),g=c,k=e.shift();k;){var l=z.yh(g,k);if(!l)break;var p=l.g();if(l.ra()){var r=z.th(g,k)||[],u=e.shift(),w=Number(u);if(void 0===u||!Number.isInteger(w)||0>w)break;if(p.prototype instanceof z.nh)l=r[w],l||(l=new p,r[w]=l),z.K(g,k,r),g=l;else{if(void 0!==e.shift())break;p=Z5a(b[a],l);r[w]=p;z.K(g,k,r)}}else if(p.prototype instanceof z.nh)r=z.th(g,
k),r||(r=new p,z.K(g,k,r)),g=r;else{if(void 0!==e.shift())break;p=Z5a(b[a],l);z.K(g,k,p)}k=e.shift()}});return c};z.q(u7,z.Ch);z.f=u7.prototype;z.f.ca=function(){return""};z.f.ea=function(){return""};z.f.cU=z.h(579);z.f.ha=function(){return u7.prototype};z.f.fa={name:"PlacementsResponse",ia:!1,fields:{placements:{name:"placements",g:function(){return q7},ra:z.U,h:1}},ka:{}};z.q(v7,z.L);v7.prototype.ca=function(){return""};v7.prototype.ea=function(){return""};v7.prototype.ha=function(){return v7.prototype};
v7.prototype.fa={name:"PlacementsRequestQuery",ia:!1,fields:{requestContext:{name:"requestContext",g:function(){return z.gq},h:1},slots:{name:"slots",g:function(){return z.iq},ra:z.U,h:2}},ka:{}};z.SW.prototype.oW=z.X(594,function(a){a!=this.cQ&&this.Ab&&(this.Ab.fi.contentEditable=a);this.cQ=a});z.WF.prototype.fX=z.X(585,function(a){this.Jn=a;return this});z.aG.prototype.fX=z.X(584,function(a){this.Jn=a;return this});
z.HF.prototype.W5=z.X(583,function(a){a=w7(a);if(!a)return null;a=x7(a)&&x7(a).io();return a?(a=a.jc())&&a.length?a[0].getName():null:null});u7.prototype.cU=z.X(579,function(){return z.J(this,"placements")});z.mD.prototype.cU=z.X(578,function(a,b){var c=this;a=a6a(b6a(new v7,a),b);a=(new t7).wk(a);var d=this.ma.la(z.Gza,{},a);return z.nD(this,d,function(){return z.t(c.pa.get(d,{background:!0}),function(a){a=c.Ka.mc(u7,a);c.Aa.rc(a);return a})})});
z.hx.prototype.Qp=z.X(495,function(){return z.J(this,"note")});z.gD.prototype.Qp=z.X(494,function(a){return this.oc("Note",a)});z.Pr.prototype.my=z.X(464,function(){return z.J(this,"replyId")});z.hx.prototype.my=z.X(463,function(){return z.J(this,"replyId")});z.Nr.prototype.hz=z.X(462,function(a){return z.K(this,"highlight",a)});z.Nr.prototype.QT=z.X(461,function(){return z.J(this,"highlight")});z.Nr.prototype.rv=z.X(460,function(a){return z.K(this,"author",a)});
z.Pr.prototype.rv=z.X(459,function(a){return z.K(this,"author",a)});z.Nr.prototype.hK=z.X(458,function(){return z.J(this,"author")});z.Pr.prototype.hK=z.X(457,function(){return z.J(this,"author")});z.Nr.prototype.WC=z.X(456,function(){return z.J(this,"highlightId")});z.Nr.prototype.Qs=z.X(455,function(a){return z.K(this,"state",a)});z.Pr.prototype.Qs=z.X(454,function(a){return z.K(this,"state",a)});z.bx.prototype.Qs=z.X(453,function(a){return z.K(this,"state",a)});
z.Nr.prototype.zg=z.X(452,function(){return z.J(this,"noteId")});z.Pr.prototype.zg=z.X(451,function(){return z.J(this,"noteId")});z.hx.prototype.zg=z.X(450,function(){return z.J(this,"noteId")});z.hr.prototype.sv=z.X(449,function(a){return z.K(this,"authorId",a)});z.Nr.prototype.sv=z.X(448,function(a){return z.K(this,"authorId",a)});z.Pr.prototype.sv=z.X(447,function(a){return z.K(this,"authorId",a)});z.Fp.prototype.Ke=z.X(343,function(){return z.J(this,"catalogId")});
z.kK.prototype.Ke=z.X(342,function(){return z.J(this,"catalogId")});z.bK.prototype.Ke=z.X(341,function(){return z.J(this,"catalogId")});z.$J.prototype.Ke=z.X(340,function(){return z.J(this,"catalogId")});z.ZL.prototype.Ke=z.X(339,function(){return z.J(this,"catalogId")});z.GJ.prototype.Ke=z.X(338,function(){return z.J(this,"catalogId")});z.EL.prototype.Ke=z.X(337,function(){return z.J(this,"catalogId")});z.zK.prototype.Ke=z.X(336,function(){return z.J(this,"catalogId")});
z.wL.prototype.Ke=z.X(335,function(){return z.J(this,"catalogId")});z.vL.prototype.Ke=z.X(334,function(){return z.J(this,"catalogId")});z.uL.prototype.Ke=z.X(333,function(){return z.J(this,"catalogId")});z.hr.prototype.Ke=z.X(332,function(){return z.J(this,"catalogId")});z.hx.prototype.Ke=z.X(331,function(){return z.J(this,"catalogId")});z.sH.prototype.Ke=z.X(330,function(){return z.J(this,"catalogId")});z.zo.prototype.dU=z.X(83,function(){return z.J(this,"point")});var l6a=/(?:https?:\/\/|www\.)\w[\w~#-@![\]]*/g;
z7.prototype.dU=function(){var a=window.document.body;return z.gg(a,this.ni.node)?this.ni:this.Uk&&z.gg(a,this.Uk)?z.LM(this.DQ,this.Uk):this.Pe&&(a=z.hs(this.Gta,this.Pe))?z.LM(this.DQ,a):null};z.q(B7,z.pm);B7.prototype.FL=function(){if(!this.ik)return null;var a=this.ik.dU();if(!a)return null;var b=this.nm.dU();return b?z.hn(a.node,a.offset,b.node,b.offset):null};z.q(C7,z.L);z.f=C7.prototype;z.f.ca=function(){return""};z.f.ea=function(){return""};z.f.ib=function(){return z.J(this,"content")};
z.f.hd=function(a){return z.K(this,"content",a)};z.f.Ib=function(){return z.J(this,"title")};z.f.Pc=function(a){return z.K(this,"title",a)};z.f.hK=function(){return z.J(this,"author")};z.f.rv=function(a){return z.K(this,"author",a)};z.f.getDate=function(){return z.J(this,"date")};z.f.setDate=function(a){return z.K(this,"date",a)};z.f.Hb=function(){return z.J(this,"collection")};z.f.setVersion=function(a){return z.K(this,"version",a)};z.f.jM=function(a){return z.K(this,"template",a)};
z.f.Yd=function(){return z.J(this,"subtitle")};z.f.Ef=function(a){return z.K(this,"subtitle",a)};z.f.ha=function(){return C7.prototype};
z.f.fa={name:"TextshotInfo",ia:!1,fields:{content:{name:"content",g:z.V,h:1},altText:{name:"altText",g:z.V,h:2},title:{name:"title",g:z.V,h:3},author:{name:"author",g:z.V,h:4},date:{name:"date",g:z.V,h:5},authorAvatarId:{name:"authorAvatarId",g:z.V,h:6},collection:{name:"collection",g:z.V,h:7},collectionAvatarId:{name:"collectionAvatarId",g:z.V,h:8},collectionLogoId:{name:"collectionLogoId",g:z.V,h:9},collectionBackgroundColor:{name:"collectionBackgroundColor",g:z.V,h:10},collectionHighlightColor:{name:"collectionHighlightColor",
g:z.V,h:11},version:{name:"version",g:z.W,h:12},base64:{name:"base64",g:z.BH,h:13},template:{name:"template",g:z.V,h:14},mainStat:{name:"mainStat",g:z.V,h:15},mainStatTitle:{name:"mainStatTitle",g:z.V,h:16},subtitle:{name:"subtitle",g:z.V,h:17},icon:{name:"icon",g:z.V,h:18},imgKey:{name:"imgKey",g:z.V,h:19}},ka:{}};var B7a={MTa:"quote-respond"};z.q(E7,z.P);z.f=E7.prototype;z.f.xk=function(){return this.vm.xk()};
z.f.na=function(){E7.ya.na.call(this);z.Qw(this,this.L_,"data-redirect-type-quote",this.axa,this);this.Ta(this.Id,"click",this.zw,this);z.PE(this.$a)&&z.Tv()&&this.Ta(this.Id,"mouseover",this.vua,this);this.$a.Ya().Wr()&&!this.$a.Mb()&&z.v(this.xe.load(this.$a.Na()),z.Kw);var a=this.xk();a&&(z.Qw(this,a,"quote",this.sua,this),z.Qw(this,a,"quote-respond",this.tua,this),z.Qw(this,a,"show",this.Q3,this),z.Qw(this,a,"hide",this.uxa,this))};
z.f.axa=function(a){var b=z.yE(this.vm,this.xk().wx);b&&(a.url=new z.Nd(this.ma.la(z.OCa,{postId:this.$a.Na()},{paragraphs:JSON.stringify([b.ty.Jb().Pb()]),startOffset:b.start,endOffset:b.end})))};z.f.zw=function(a){z.es(a.target,function(a){if(a===this.Id)return!0;var c=z.AB(a);if(3==c)return!0;if(7==c){if(c=v6a(this,a))if(F7(this,c),z.Tv())H7(this,c);else{var d=new z.AE;t6a(this,c,a,d)}return!0}return!1}.bind(this))};
z.f.vua=function(a){z.es(a.target,function(a){if(a===this.Id)return!0;var c=z.AB(a);if(3==c)return!0;if(7==c){c=z.vn();if(!(c&&!c.isCollapsed()||this.xk()&&this.xk().Um())&&(c=v6a(this,a))){var d=this.Id.querySelector('.markup--quote[name~\x3d"'+c.bj()+'"]');a=new z.CE(a,100);t6a(this,c,d,a);F7(this,c)}return!0}return!1}.bind(this))};
z.f.Q3=function(){var a=z.vn();a&&!a.isCollapsed()&&F7(this,null);if(z.PE(this.$a)&&(a=z.yE(this.vm,this.xk().wx))){var a=z.Fva(this.xe,a.ty,a.start,a.end),b=this.xk().Sa().querySelector(".js-highlightMenuQuoteButton");z.cd(b,"is-active",!!a)}};z.f.uxa=function(){this.Cp&&F7(this,null)};
z.f.sua=function(){if(z.PE(this.$a)){var a=z.tE(this.xk());if(a){var b=a.range,c=a.XIa,a=this.xk().Sa().querySelector(".js-highlightMenuQuoteButton"),d=z.Rc(a,"is-active"),b=z.yE(this.vm,b);z.v(z.t(this.xe.toggle(b.ty,b.start,b.end,!c),function(a){z.oKa();d?z.vE(this.xk()):H7(this,a);var b=c?"selection_menu":"quote_click_menu";I7(this,a.bj(),!d,b)},this),z.Kw)}}};
z.f.tua=function(){if(z.PE(this.$a)&&z.bm.supportsEdit){var a=z.tE(this.xk());if(a){var b=z.yE(this.vm,a.range);z.v(z.t(this.xe.create(b.ty,b.start,b.end,1,!0),function(a){I7(this,a.bj(),!0,"selection_menu_quote_respond");this.za("quote-respond",a,b.ty.name)},this),z.Kw)}}};
z.f.Cua=function(a){var b=this.Cp,c=G7(this,b),d=b.Ed(),e=b.Be(),b=a.query(".js-quoteAttributions-pileOn"),g=z.Rc(b,"is-active");z.v(z.t(this.xe.toggle(c,d,e,!0),function(b){var l=a.query(".js-quoteAttributions-pileOn");z.dd(l,"is-active");if(l=z.pE(this.xe,c,d,e)){var p=s6a(this,l),r=a.query(".js-quoteAttributions-info");z.Pv(r,k6a,p)}else a.Lc();!g&&z.Tv()&&(a.Lc(),H7(this,l));l=z.Tv()?"quote_hover":"quote_click_mobile";I7(this,b.bj(),!g,l)},this),z.Kw)};
z.f.Dua=function(){if(z.PE(this.$a)&&z.bm.supportsEdit){var a=G7(this,this.Cp),b=this.Cp.Ed(),c=this.Cp.Be();z.v(z.t(this.xe.create(a,b,c,1,!0),function(b){I7(this,b.bj(),!0,"quote_respond");this.za("quote-respond",b,a.name)},this),z.Kw)}};z.f.Eua=function(){var a=x6a(this,this.Cp);a&&z.Pva(this.vm,a)};
z.f.sfa=function(){var a=new B7(this.Id),b=this.xe.bu,c=Object.keys(b).concat(this.Uba);z.eb(c);c.forEach(function(a){var c=b[a]||[],g=this.$a;if(g=(a=g.Id&&z.hs(g.Id,a))&&this.$a.aj(a))j6a(g,c),a.innerHTML=z.xt(g,z.bm,z.bwa(this.$a)),z.yya(this.kAa,a)},this);this.Uba=Object.keys(b);(a=a.restore())&&a.select()};z.q(J7,z.Ow);z.f=J7.prototype;
z.f.load=function(a){if(!z.Rp())return z.Lc([]);this.nb=a;this.Ih||(this.Ih=z.v(z.t(this.sl.get(this.ma.la(z.GCa,{postId:a}),{background:!0}),this.iAa,this),z.Kw));return this.Ih.$c()};z.f.aq=function(){return this.Rba};z.f.Kj=function(){return this.Qea};z.f.QT=function(a){return this.fda[a]||null};z.f.Qp=function(a,b){return z.uN(K7(this,b),a)};z.f.hz=function(a,b){this.fda[a]=b};z.f.Na=function(){return this.nb};
z.f.iAa=function(a){var b=a.references.User;this.Qea=a.post.visibility;var c=a.value;if(c)for(var d=0;d<c.length;d++){var e=c[d];if("HIDDEN"!=e.state){var g=e.replies,k=b;if(g)for(var l=0;l<g.length;l++){var p=g[l],r=p.authorId||null;p.author=r&&k[r]||null}g=e.anchor;k=e.authorId||null;e.author=k&&b[k]||null;g=K7(this,g);e=z.Or(e);g.add(z.lC(this.Aa,e))}}if(a=a.highlights)for(b=0;b<a.length;b++)this.hz(a[b].id,z.fo.Jb(z.Qr,a[b]));this.Rba=!0};z.m(N7,z.P);N7.prototype.na=function(){var a=this;z.P.prototype.na.call(this);z.t(this.eb.cU(this.$Aa,this.Wza),function(b){b.placements&&b.placements.forEach(a.pva,a)})};N7.prototype.pva=function(a){if(this.isActive()){var b;switch(a.location){case 1:b=this.Oa.query(".js-postFooterPlacements");if(!b)break;z.Pv(b,z.iQ,{items:a.items,context:9});z.T(b).ba("show-more-recommendations",this.GCa,this);break;case 2:(b=this.Oa.query(".js-readNextMetabarRight"))&&z.Pv(b,z.iQ,{items:a.items,context:2})}}};
N7.prototype.GCa=function(a){z.mx(z.tGa,{});var b=this.Oa.query(".js-moreRecommendations");b&&(z.ks(b),z.js(a.target))};z.m(O7,z.P);z.f=O7.prototype;
z.f.na=function(){var a=this;z.P.prototype.na.call(this);this.np&&(z.Qw(this,this.np,z.eHa,function(){z.Tc(a.oa(),"is-abovePostActions");a.aQ=!0}),z.Qw(this,this.np,z.fHa,function(){z.$c(a.oa(),"is-abovePostActions");a.aQ=!1}));z.T(this.oa()).ba("dismiss-meter",this.ut,this).ba("expand-meter",this.Ata,this);var b=this.ph.postIds&&1<this.ph.postIds.length,c=z.Hp().isMobile&&!z.Hp().isTablet;if(b||c)this.dw=(0,window.setTimeout)(this.ut.bind(this),C7a);z.t(z.lm(300),this.KAa,this)};
z.f.Ca=function(){this.kh&&(this.kh.cancel(),this.kh=null);this.dw&&((0,window.clearTimeout)(this.dw),this.dw=null);z.P.prototype.Ca.call(this)};z.f.ut=function(){var a=this;this.kh=new z.sz(this.oa(),{name:this.aQ?z.Hp().isMobile?"pop-shift-down-35":"pop-shift-down-44":"pop-shift-down-0",duration:550,timing:"ease-in-out"});z.t(this.kh,function(){z.js(a.oa());z.ks(a.Oa.query(".js-openInAppButton"))});this.kh.start()};
z.f.Ata=function(a){a=a.target;var b=this.query(D7a),c=this.query(E7a);z.js(a);z.Tc(b,"is-visible");this.dw&&((0,window.clearTimeout)(this.dw),this.dw=null);z.Pv(c,z.Wwa);z.$c(c,"u-xs-hide");z.mx(z.BGa,{unlockCount:this.ph.postIds.length})};
z.f.KAa=function(){var a=this;this.Oa.oa().appendChild(this.oa());z.t((new z.sz(this.oa(),{name:this.aQ?z.Hp().isMobile?"pop-shift-up-35":"pop-shift-up-44":"pop-shift-up-0",duration:800,timing:"ease-in-out"})).start(),function(){if(a.ph&&a.ph.postIds&&a.ph.postIds.length){for(var b=a.qb(".js-meterThumbnail"),c=new z.tc,d=0;d<a.ph.postIds.length;d++)z.t(c,a.QY.bind(a,b[d],d==b.length-1));c.callback()}})};
z.f.QY=function(a,b){b=new z.sz(a,{name:b?"pulse-grow-50-110":"pulse-grow-50-105",duration:800+(b?200:0)});var c=z.t(new z.sz(a.querySelector(".js-thumbnailImage"),{name:"fade-in",duration:800}),function(){z.Tc(a,"is-read")}),d=new z.sz(a.querySelector(".js-thumbnailText"),{name:"color-light-to-white",duration:800});return new z.cm([b.start(),c.start(),d.start()])};var C7a=6E3,E7a=".js-dismissMeterIndicator",D7a=".js-moreInfo";P7.prototype.fT=function(a,b,c){return new E7(a,b,c)};P7.prototype.bs=function(){return B7a};M6a.prototype.get=function(a){return Q7(this,a)};z.q(R7,z.SW);z.f=R7.prototype;z.f.XI=!1;z.f.iB="";z.f.YI=0;z.f.ss=z.U;z.f.zg=function(){return this.q1};z.f.save=function(){this.ib().length<=this.um&&this.vl()};z.f.Gb=function(){(0,window.clearTimeout)(this.YI);R7.ya.Gb.call(this)};
z.f.na=function(){function a(a){a.stopPropagation()}R7.ya.na.call(this);this.iB=this.ib();this.hd(this.iB);this.Kx(13,this.u1,this);this.Kx(27,this.v1,this);this.Ab.Ta("blur",this.t1,!1,this);var b=this.Ab.Sa();z.dw(b,"keydown",a);z.dw(b,"keyup",a);z.dw(b,"keypress",a)};z.f.g8=function(a){return a};
z.f.vl=function(){if(this.isEnabled()){var a=this.ib().trim();if(a){this.oW(!1);var b=this.Kia(),a=this.Jia(a);this.za("saving",a);z.zc(z.v(z.t(this.sl.post(b,a.Pb()),this.Vxa,this),this.Txa.bind(this,a)),this.oW.bind(this,!0))}}};z.f.Vxa=function(a){this.za("save",this.g8(a.value))};z.f.Txa=function(a,b){this.za("fail",a);this.Fa.error(P6a());z.Kw(b)};z.f.u1=function(a){if(this.Fr&&z.AX(this.Fr))return!1;a.shiftKey||(a.preventDefault(),this.save());return!0};
z.f.v1=function(a){if(this.Fr&&z.AX(this.Fr))return!1;a.preventDefault();this.hd(this.iB);this.za("cancel");return!1};z.f.t1=function(){this.XI&&(this.ib().length>=this.um?(0,window.confirm)(this.Nia())?(this.hd(this.iB),this.za("cancel")):this.focus():this.YI=(0,window.setTimeout)(this.vl.bind(this),100))};z.q(S7,R7);z.f=S7.prototype;z.f.JY=null;z.f.jba=null;z.f.NY=null;z.f.dk=null;z.f.f0=null;z.f.e0=null;z.f.eda=null;z.f.hz=function(a){this.dk=a;this.f0=a.startIndex;this.e0=a.endIndex;this.eda=a.content;return this};z.f.Nia=function(){var a=z.n("Your note is too long; do you want to abandon your changes?");return(0,z.y)(""+a)};z.f.g8=function(a){var b=z.Nv();a=z.Or(a).rv(b).sv(b.mb());this.dk&&a.WC()&&this.xf.hz(a.WC(),this.dk);var b=this.xf,c;c=z.lC(b.Aa,a);K7(b,c.he()).add(c);return a};
z.f.Kia=function(){return this.zg()?this.ma.la(z.HCa,{postId:this.nb,noteId:this.zg()}):this.ma.la(z.FCa,{postId:this.nb})};z.f.Jia=function(a){var b=z.Nv();a=(new z.Nr({content:a,anchor:this.JY,anchorContent:this.jba,anchorImage:this.NY?this.NY.Pb():null,replies:[],createdAt:Date.now()})).rv(b);null!=this.f0&&null!=this.e0&&(b=new z.Qr({anchor:this.JY,startIndex:this.f0,endIndex:this.e0,content:this.eda}),a.hz(b));return a};z.q(T7,R7);T7.prototype.Nia=function(){var a=z.n("Your reply is too long; do you want to abandon your changes?");return(0,z.y)(""+a)};T7.prototype.g8=function(a){var b=z.Nv();a=z.Hja(a).rv(b).sv(b.mb());z.J(this.xf.Qp(a.zg(),this.Pe),"replies").push(a);return a};T7.prototype.Kia=function(){return this.ofa?this.ma.la(z.KCa,{postId:this.nb,noteId:this.zg(),replyId:this.ofa}):this.ma.la(z.JCa,{postId:this.nb,noteId:this.zg()})};
T7.prototype.Jia=function(a){var b=z.Nv();return(new z.Pr({replyId:"",postId:this.nb,noteId:this.zg(),content:a,createdAt:Date.now()})).rv(b)};z.q(V7,z.P);z.f=V7.prototype;
z.f.na=function(){V7.ya.na.call(this);z.T(this.oa()).ba("show-note-editor",this.i3,this).ba("hide-note-editor",this.b0.bind(this,!0)).ba("show-reply-editor",this.UCa,this).ba("hide-reply-editor",this.Zua,this).ba("save-note",this.ABa,this).ba("save-reply",this.BBa,this).ba("highlight-quote",this.bva,this).ba("dismiss-note",this.Yba.bind(this,!0),this).ba("delete-note",this.Yba.bind(this,!1),this).ba("delete-reply",this.Psa,this).ba("previous-highlight-tip",this.gAa,this).ba("next-highlight-tip",this.Dwa,
this);c7a(this);this.Bj&&r7(this.Bj)&&(b7a(this),z.Qw(this,r7(this.Bj),"add",this.Sxa,this));if(this.r2&&this.rda&&this.sda){var a=this.query(".js-inlineNewPostControl"),b=this.r2,c=this.$a.Na(),d=new z.OS(this.qa);d.$L("web-inline-quote-responses");d.Wa(a);d.wG=!0;d.XZ=!0;d.RZ=!0;d.jM(m6a);d.hB=b;d.dM(c);z.PS(d,!0);this.Hc=d;this.Hc.ua();a=X7(this.wI);this.za("set-active-highlight",this.Pe,a)}this.dk&&(this.i3(),this.Mf&&this.Mf.focus());Y7(this,0)};
z.f.Ca=function(){this.cr&&this.cr.i5();(this.dk||this.wI)&&this.za("reset-highlight",this.Pe,null);V7.ya.Ca.call(this)};z.f.Gb=function(){z.tx(this.oa());z.Vf(this.oa());z.fm(this.Hc);z.fm(this.Mf);z.fm(this.cr);z.gm(z.nb(this.fk));this.cr=this.fk=this.Mf=this.Hc=null;V7.ya.Gb.call(this)};z.f.po=function(){if(this.Mf&&this.Mf.ib())return!0;for(var a=z.nb(this.fk),b=0;b<a.length;b++)if(a[b]&&a[b].ib())return!0;return this.Hc&&!this.Hc.isDismissable()?!0:!1};
z.f.Tq=function(){var a=[],b=[],c=[],d=this.mB&&(this.dk||this.wI);d||(this.Iw?(a=this.xe?s7(this.xe,this.Iw.quotes):[],b=this.Iw.notes,c=this.Iw.responses):(b=this.xf?z.QC(K7(this.xf,this.Pe)):[],this.q1||(this.xe?(a=this.xe,a=s7(a,a.bu[this.Pe]||[])):a=[],c=this.Bj?y7(this.Bj,this.Pe):[])));return z.Rv(Z6a,{post:this.$a.Ya(),quotes:a,notes:b,responses:c,R9:!!this.r2,tW:d,nM:this.mB,rE:this.vga,OJa:z.OE(this.$a)})};
z.f.Sxa=function(){var a=this.query(".js-postList"),b=z.Rv(Y6a,{responses:y7(this.Bj,this.Pe)});z.Yf(b,a);b7a(this)};
z.f.i3=function(){if(this.mB){if(!this.Mf){var a=this.query(".js-noteEditor"),b=z.Qv(W6a),a=this.Mf=new S7(this.qa,a,this.$a.Na(),null,b),b=this.Pe,c=this.$a.aj(this.lf.get(this.Pe)),d=c.Ia(),c=4==c.type?c.Ce():null;a.JY=b;a.jba=d;a.NY=c;(a=this.dk)&&this.Mf.hz(a);z.Qw(this,this.Mf,"saving",this.zya,this);z.Qw(this,this.Mf,"fail",this.sxa,this);z.Qw(this,this.Mf,"save",this.uya,this)}z.Tc(this.query(".js-noteActions"),"is-noteEditorVisible");this.Mf&&this.Mf.focus()}};
z.f.ABa=function(){this.Mf&&this.Mf.save()};z.f.zya=function(a){this.Mf.hd("");var b=this.query(".js-notesList");a={note:a,post:this.$a.Ya(),tW:this.mB,nM:this.mB};a=z.Rv(U7,a);b.appendChild(a);z.$c(b,"is-empty");c7a(this);this.b0()};z.f.uya=function(a){var b=this.query(".js-notesList").lastChild;a=a.zg();z.Tc(b,"js-note-"+a);b.setAttribute("data-note-id",a);(b=b.querySelector(".js-deleteNote"))&&b.setAttribute("data-action-value",a)};
z.f.sxa=function(){var a=this.query(".js-notesList");a.removeChild(a.lastChild);z.Tc(a,"is-empty");this.i3()};z.f.b0=function(a){a?this.za("close"):this.Mf&&(this.Mf.ib()&&this.Mf.hd(""),z.$c(this.query(".js-noteActions"),"is-noteEditorVisible"))};z.f.UCa=function(a){(a=W7(a.target))&&this.mB&&d7a(this,a)};z.f.BBa=function(a){a=W7(a.target);(a=this.fk[a])&&a.save()};
z.f.Aya=function(a){var b=a.zg();this.fk[b]&&this.fk[b].hd("");var c=this.xf.Qp(b,this.Pe).author.userId==a.author.userId,d=this.query(".js-note-"+a.zg()+" .js-repliesList");a={note:a,post:this.$a.Ya(),$ja:c};a=z.Rv(U7,a);d.appendChild(a);z.$c(d,"is-empty");e7a(this,b)};z.f.vya=function(a){var b=this.query(".js-note-"+a.zg()).querySelector(".js-repliesList").lastChild;a=a.my();z.Tc(b,"js-reply-"+a);(b=b.querySelector(".js-deleteNote"))&&b.setAttribute("data-action-value",a)};
z.f.txa=function(a){var b=this.query(".js-note-"+a.zg()+" .js-repliesList");b.removeChild(b.lastChild);z.Tc(b,"is-empty");d7a(this,a.zg())};z.f.Zua=function(a){(a=W7(a.target))&&e7a(this,a)};z.f.bva=function(a){a=a.target;var b=a.getAttribute("data-quote-creator-id"),c=Q7(this.lf,this.Pe);c&&(this.cr&&this.cr.i5(),this.cr=g7a(this,c,a,function(){f7a(this,b,!1);z.fm(this.cr);this.cr=null}),f7a(this,b,!0))};
z.f.ava=function(a){var b=Q7(this.lf,this.Pe);(a=this.xf.Qp(a.target.getAttribute("data-note-id"),this.Pe))&&b&&(b=(b=a.WC())?this.xf.QT(b):null,this.za("set-active-highlight",this.Pe,b))};z.f.cva=function(a){var b=Q7(this.lf,this.Pe),c;c=this.Bj;a=a.target.getAttribute("data-post-id");c=r7(c)?z.uN(r7(c),a):null;b&&c&&(b=w7(c))&&(b=x7(b)&&x7(b).io())&&(c=b.jc())&&c.length&&(b=X7(b),this.za("set-active-highlight",this.Pe,b))};
z.f.O3=function(){var a=null;this.wI&&(a=X7(this.wI));this.dk&&(a=this.dk);this.za("reset-highlight",this.Pe,a)};
z.f.Yba=function(a,b){b=b.value;var c=this.xf.Qp(b,this.Pe),d=this.query(".js-note-"+b);if(c&&d){z.js(d);this.O3();this.qb(".js-note-item").every(function(a){return z.Rc(a,"u-hide")})&&this.b0(!0);var e=L7(this.xf,c,"HIDDEN");z.v(e.Il,function(b){this.xa.ua(a?Q6a():R6a(),"error");e.JL();z.ks(d);(400>b.status||499<b.status)&&L7(this.xf,c,"NEW")},this);z.t(this.xa.ua(a?T6a():U6a(),{type:"success",sE:!0}),function(){this.xa.Lc();e.JL();L7(this.xf,c,"NEW");z.ks(d)},this)}};
z.f.Psa=function(a){var b=a.value,c=this.query(".js-reply-"+b),d=W7(a.target);if(d&&c){z.js(c);var e=M7(this.xf,b,d,this.$a.Na(),this.Pe,"HIDDEN");z.v(e.Il,function(){this.xa.ua(S6a(),"error");e.JL();z.ks(c);M7(this.xf,b,d,this.$a.Na(),this.Pe,"")},this);z.t(this.xa.ua(V6a(),{type:"success",sE:!0}),function(){this.xa.Lc();e.JL();M7(this.xf,b,d,this.$a.Na(),this.Pe,"");z.ks(c)},this)}};z.f.gAa=function(){Y7(this,this.LP-1)};z.f.Dwa=function(){Y7(this,this.LP+1)};z.q(Z7,z.P);z.f=Z7.prototype;z.f.na=function(){Z7.ya.na.call(this);var a=[];z.OE(this.$a)&&a.push(this.xf.load(this.nb));this.xda||(a.push(this.xe.load(this.nb)),a.push(this.Bj.load(this.nb)));this.nw=z.t(z.t(z.t(z.CR(a),function(){this.nw=null},this),this.render,this),this.Mra,this);z.Qw(this,this.Fb,"resize-end",this.Xf,this)};z.f.Ca=function(){this.nw&&this.nw.cancel();Z7.ya.Ca.call(this)};z.f.Gb=function(){this.nw=null;Z7.ya.Gb.call(this)};
z.f.render=function(){N6a(this.lf,function(a,b){$7(this,b)},this)};z.f.Xf=function(){N6a(this.lf,function(a,b){n7a(this,b)},this)};z.f.Mra=function(){var a=this.xe.pp;z.Qw(this,a,"add",this.zea,this);z.Qw(this,a,"remove",this.zea,this);(a=r7(this.Bj))&&z.Qw(this,a,"add",this.rya,this)};z.f.zea=function(a){h7a(this,Object.keys(z.Jva(this.xe,a instanceof Array?a:[a])))};z.f.rya=function(a){h7a(this,(a instanceof Array?a:[a]).map(this.Bj.W5,this.Bj))};
z.f.Tq=function(a){var b=window.document.createElement("div");b.className="notesMarkers";a.appendChild(b);return b};z.f.VH=function(a,b){z.wb(a,{startIndex:Math.min(a.startIndex,b.startIndex),endIndex:Math.max(a.endIndex,b.endIndex),notes:a.notes.concat(b.notes),quotes:a.quotes.concat(b.quotes),responses:a.responses.concat(b.responses)})};z.q(a8,z.P);z.f=a8.prototype;
z.f.na=function(){a8.ya.na.call(this);this.Ta(this.Oa.oa(),"click",this.ewa,this,!0);z.T(this.RH).ba("select-anchor",this.Gya,this);var a=this.$a.Ya();if(a.Wr()&&!this.$a.Mb()){var b=z.yp(a),b=2==a.visibility&&b&&!z.J(b.Oj(),"memberOfMembershipPlanId");a.allowResponses&&!b&&z.v(this.Bj.load(this.$a.Na(),"best"),z.Kw);z.v(this.xe.load(this.$a.Na()),z.Kw)}a.Oj().gK()&&(this.zQ=z.t(this.xf.load(this.$a.Na()),this.Wxa,this));this.S0&&c8(this,null);z.Qw(this,this.tb,"historyUpdate",function(){c8(this,
z.EE())},this);this.Re&&z.Qw(this,this.Re,"highlight",this.Uxa,this)};z.f.Gb=function(){z.fm(this.Lh);this.Lh=null;z.fm(this.im);this.im=null;this.RH&&z.T(this.RH).clear("select-anchor");this.zQ&&this.zQ.cancel();this.zQ=null;a8.ya.Gb.call(this)};z.f.VJa=function(a,b){b8(this,b,null,null,a)};z.f.WLa=function(){this.Lh&&this.Lh.Xf()};z.f.po=function(){if(!this.im)return!1;var a=this.im.ib();return a?a.po():!1};z.f.Rxa=function(a){a.subscribe("add",this.Fga,this);a.subscribe("remove",this.Fga,this)};
z.f.Fga=function(a){(z.oa(a)?a:[a]).forEach(function(a){$7(this.Lh,a.he())},this)};z.f.Wxa=function(){var a=(0,z.Ka)();this.zQ=null;c8(this,z.EE());this.Ta(this.jm,z.iI,this.F1,this);z.fy(z.$Ea,(0,z.Ka)()-a)};z.f.F1=function(a){(a=a.target.getAttribute("name"))&&Q7(this.lf,a)&&n7a(this.Lh,a)};z.f.Uxa=function(){if(this.Re){var a=t7a(this,this.Re.wx);z.vE(this.Re);a&&(a=a.highlight,this.Efa(a.anchor,a),b8(this,a.anchor,a))}};
z.f.ewa=function(a){if(this.im){var b=a.target;if(!z.gg(this.im.oa(),b)){var c=this.im.ib(),d;if(!(d=!c)){a:if(c.Mf&&c.Mf.ib())c=!0;else{d=z.nb(c.fk);for(var e=0;e<d.length;e++)if(d[e]&&d[e].ib()){c=!0;break a}c=c.Hc&&!c.Hc.dj()?!0:!1}d=!c}d&&(c=this.im&&this.im.Pn,d="select-anchor"==b.getAttribute("data-action"),this.A2(),c&&d&&z.gg(c,b)&&a.stopPropagation())}}};
z.f.Jn=function(a){if(!z.Vv()){var b=a.Pn,c=z.ow(b);a.Nl();a=a.oa();var d=z.ow(a),e=window.innerHeight,g=window.innerWidth,k=this.Oa.query(".js-metabar"),l=0;k&&(l=z.ow(k).height);d.height>=e-l?A6a(a):(z.kw(b),b=c.top+d.height>=e?z.lw().top+e-d.height-10:z.kw(b),c=z.ow(this.RH).left+10,c+d.width>=g&&(c=g-d.width-10),a.style.top=b+"px",a.style.left=c+"px")}};z.f.A2=function(){z.fm(this.im);this.im=null};
z.f.Gya=function(a){var b=z.es(a.target,function(a){return z.Rc(a,"js-paragraphControl")},this.Jea),b=o7a(this.Lh,a.value,b);b8(this,a.value,null,null,null,b)};z.f.Efa=function(a,b){if(this.$a.Mb()){var c=z.vn();this.rR=(c=c&&O6a(this.lf,c.Tf()))&&new B7(c)}s7a(this,a,b)};z.f.hBa=function(a,b){s7a(this,a,b);this.$a.Mb()&&this.rR&&(a=this.rR.restore())&&a.select();this.rR=null};
z.f.ix=function(a){if(this.lf&&(a=Q7(this.lf,a))){a=Math.max(z.kw(a),0);var b=window.document.body;this.kh&&this.kh.cancel();this.kh=new z.co(b,"scrollTop",600,a)}};u7a.prototype.fT=function(a,b,c){return new a8(a,b,c)};z.m(d8,z.P);z.f=d8.prototype;z.f.qc=function(a){this.va=a};z.f.jM=function(a){this.Ph=a};z.f.ZKa=function(a){this.d3=a};z.f.$Ka=function(a){this.Rfa=a};
z.f.na=function(){this.oa()?(z.P.prototype.na.call(this),z.T(this.oa()).ba("show-responses-stream-editor",this.Sya,this).ba("show-other-responses",this.Xfa,this),z.Pv(this.oa(),this.Ph,{post:this.va}),this.va.Wr()&&z.v(z.t(z.t(z.t(i6a(this.eb,this.va.Bb(),"best"),this.mfa.bind(this,"best")),this.PAa,this),function(){this.Z3.n9&&this.Xfa()},this),z.Kw)):z.Kw("Attempted to initialize ResponsesStreamControl without root element.")};z.f.Ca=function(){z.T(this.oa()).clear("show-other-responses");z.P.prototype.Ca.call(this)};
z.f.mfa=function(a,b){this.isActive()&&(b=b.Oe,"best"==a?(a=this.query(".js-responsesStream"),z.Qw(this,b,"add",this.aea.bind(this,b)),this.aea(b)):a=this.query(".js-responsesStreamOther"),b&&(z.Tp()||0<b.Le())&&a&&(z.Pv(a,z.iQ,{items:z.QC(b),context:2}),b=new z.rS(this.qa,b),b.Wa(a),b.Ad(2),this.track(b),z.ks(this.query(".js-responsesStreamWrapper"))),this.Rfa&&(a=z.kw(a),z.hw(window.document.body,0,a)))};
z.f.PAa=function(){var a=this.query(".js-inlineNewPostControl"),b=this.query(".js-responsesLoggedOutPrompt");z.Tp()?a?(this.Hc=z.PS(c6a((new z.OS(this.qa)).$L("web-inline-post-response").dM(this.va.Bb()),z.Ov(z.ii,{post:this.va,gW:!0})),this.d3).Wa(a),this.track(this.Hc)):b&&this.d3&&(a=z.jw(b),b=z.kw(b),z.hw(a,0,b)):b&&z.Tc(b,"u-hide")};
z.f.Xfa=function(){this.K1||(this.K1=z.zc(z.t(z.t(i6a(this.eb,this.va.Bb(),"other"),this.mfa.bind(this,"other")),function(){z.js(this.query(".js-showOtherResponses"));this.Z3.n9=!0},this),function(){this.K1=null},this))};z.f.aea=function(a){(a=a.kl)&&a.next&&"other"==a.next.filter&&!this.Z3.n9&&(z.ks(this.query(".js-responsesStreamWrapper")),z.ks(this.query(".js-showOtherResponses")))};z.f.$x=function(){this.Hc&&(z.pR(this.Hc.oa(),new z.Bn(60,0,200,0)),this.Hc.$x())};
z.f.Sya=function(){var a=this.query(".js-responsesStreamEditor"),b=this.query(".js-showResponsesStreamEditorButton");z.ls(a)&&(z.ks(a),z.js(b),this.$x())};z.q(e8,z.Ow);e8.prototype.focus=function(){this.isActive&&this.zz.focus()};e8.prototype.close=function(){this.zz&&!this.zz.closed&&this.zz.close();this.za("close");this.fg()};e8.prototype.isActive=function(){return this.zz?!this.zz.closed:!1};e8.prototype.Va=function(){this.zz=null;e8.ya.Va.call(this)};z.f=w7a.prototype;z.f.iE=function(a,b,c){var d;d=z.bm;var e=new z.hi(z.am(d)),e=new z.Nd(e.Dl(a));d=D7(e,d);this.Sw(d);z.mx(z.TI,{postId:a.id,type:b,source:c,dest:"facebook",dialogType:"native"})};z.f.g9=function(a){var b;b=z.bm;var c=new z.hi(z.am(b));a=new z.Nd(c.la(z.Du,{catalogSlug:a.Ke(),username:a.Af().Bk()}));b=D7(a,b);this.Sw(b)};z.f.h9=function(a){var b;b=z.bm;var c=new z.hi(z.am(b));a=new z.Nd(c.la(z.uu,{sequenceSlug:a.rd()}));b=D7(a,b);this.Sw(b)};
z.f.R5=function(){var a=this.ma.la(z.mCa);return this.pa.get(a)};z.f.Sw=function(a){v7a(a,"facebook-share",{width:550,height:320})};z.q(f8,z.dm);
f8.prototype.open=function(a,b){this.va=a;this.Ax=b;this.Fa=this.uG.open({bodyHtml:z.Ov(F6a,this.Ax),type:"tweet"},!0);a=this.Fa.query(".js-tweetEditor-text");b=this.qa;var c=String,d;d=z.n("Enter tweet text.");d=(0,z.y)(""+d);this.wJ=new z.wX(b,a,c(d),!0);a=new z.lU(280,!0);a.Mba=A7;this.wJ.cb(a);a=o6a(B6a,this.Ax,z.bm);this.wJ.hd(a);this.wJ.focus();y7a(this);z.T(this.Fa.dc).ba("remove-textshot",this.Jfa.bind(this,!1),this).ba("add-textshot",this.Jfa.bind(this,!0),this).ba("toggle-expand-image",this.NDa,
this);this.Fa.subscribe(z.Gy,this.zEa.bind(this))};f8.prototype.zEa=function(){var a=this.wJ.ib();if(z7a(this,a)){var b=this.SP?x7a(this):null;z.v(z.t(this.pa.post(this.ma.la(z.kCa),{tweet:a,textshotInfo:b}),function(a){a=z.Qv(D6a,{id:a.value});a=z.Ov(H6a,{PLa:a});this.xa.ua(a,{type:"success",Ok:1E4})},this),function(a){z.Kw(a);this.xa.ua(G6a(),"error")},this);z.$x(z.PEa,{postId:this.va.id,type:this.Ax.shareType,source:this.Ax.dLa,dest:"twitter",style:this.SP?"textshot":null});this.Fa.close()}};
f8.prototype.Jfa=function(a){this.SP=a;z.cd(this.Fa.query(".js-tweetEditor-imageContainer"),"u-hide",!a);z.cd(this.Fa.query(".js-tweetEditor-addTextshot"),"u-hide",a)};f8.prototype.NDa=function(){var a=this.Fa.query(".js-tweetEditor-image");z.dd(a,"tweetEditor-image--expanded")};z.f=A7a.prototype;z.f.cLa=function(a,b){var c=z.Qp(),d=a.creator||{},e=h6a(b),g=g6a(b),k=p6a(a,z.bm);(b=J6a(b.T5()))&&z.Td(k,b||"");var l={name:d.name||"",username:d.username||"",twitterScreenName:d.twitterScreenName||"",url:k.toString(),content:a.title,user:c,GLa:e,FLa:g,shareType:"highlight",dLa:"highlight_menu"};z.v(z.t(this.qa.load("tweet-dialog"),function(b){b.open(a,l)}),z.Kw);z.$x(z.TI,{postId:a.id,type:"highlight",source:"highlight_menu",dest:"twitter",dialogType:"inapp"});return!0};
z.f.iE=function(a,b,c,d,e){var g=z.Qp().userId,k="highlight"==c?B6a:z.Nja,l=z.bm,p=a.creator||{};b={content:b,name:p.name||"",username:p.username||"",twitterScreenName:p.twitterScreenName||"",mha:p.userId==g,url:p6a(a,l).toString(),collaborators:d||[]};d=d&&d.length?String(k(b,null,l)):o6a(k,b,l);k=new z.Nd("https://twitter.com/intent/tweet");z.Xd(k,"text",d);this.Sw(k);z.mx(z.TI,{postId:a.id,type:c,source:e,dest:"twitter",dialogType:"native"})};
z.f.g9=function(a){var b=z.bm,c=new z.hi(z.am(b)),c=(new z.Nd(c.la(z.Du,{catalogSlug:a.Ke(),username:a.Af().Bk()}))).toString();a=z.B(""+z.Kk(String(a.name))+((null==a.creator?null:a.creator.userId)!=b.currentUser.userId?" — "+z.Wr({twitterScreenName:null==a.creator?null:a.creator.twitterScreenName,name:null==a.creator?null:a.creator.name}):"")+" "+(""+c));b=new z.Nd("https://twitter.com/intent/tweet");z.Xd(b,"text",a);this.Sw(b)};
z.f.h9=function(a){var b=new z.hi(z.am(z.bm)),b=(new z.Nd(b.la(z.uu,{sequenceSlug:a.rd()}))).toString();a=z.B(""+z.Kk(String(a.title))+" "+(""+b));b=new z.Nd("https://twitter.com/intent/tweet");z.Xd(b,"text",a);this.Sw(b)};z.f.Sw=function(a){v7a(a,"twitter-share",{width:670,height:420})};var F7a=z.Ix,G7a=F7a.Da();z.Lx(G7a.scope("screen").add("quotes",P7).add("quote-responses",u7a).add("responses-stream-control",d8).add("notes-data",J7),"PostMeterBar",O7);z.Lx(G7a.scope("app"),"PlacementsControl",N7).add("twitter",A7a).add("facebook",w7a).add("tweet-dialog",f8);z.vN(F7a,"notes");}).call(this, _mdm);
